# Generated by Django 2.2 on 2020-04-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=250)),
                ('option_one', models.IntegerField(default=0)),
                ('option_two', models.IntegerField(default=0)),
                ('option_three', models.IntegerField(default=0)),
            ],
        ),
    ]
