# Generated by Django 2.2 on 2020-04-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='option_one',
            new_name='option_one_count',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='option_three',
            new_name='option_three_count',
        ),
        migrations.RenameField(
            model_name='vote',
            old_name='option_two',
            new_name='option_two_count',
        ),
        migrations.AddField(
            model_name='vote',
            name='option_one_text',
            field=models.CharField(default='a', max_length=20),
        ),
        migrations.AddField(
            model_name='vote',
            name='option_three_text',
            field=models.CharField(default='c', max_length=20),
        ),
        migrations.AddField(
            model_name='vote',
            name='option_two_text',
            field=models.CharField(default='b', max_length=20),
        ),
    ]
