# Generated by Django 2.2 on 2020-04-23 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote_app', '0002_auto_20200422_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='option_one_image_url',
            field=models.CharField(default='https://images.unsplash.com/photo-1515549832467-8783363e19b6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=282&q=80', max_length=250),
        ),
        migrations.AddField(
            model_name='vote',
            name='option_three_image_url',
            field=models.CharField(default='https://images.unsplash.com/photo-1515549832467-8783363e19b6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=282&q=80', max_length=250),
        ),
        migrations.AddField(
            model_name='vote',
            name='option_two_image_url',
            field=models.CharField(default='https://images.unsplash.com/photo-1515549832467-8783363e19b6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=282&q=80', max_length=250),
        ),
    ]
